name: test_app
description: "Test app for Media Manager.project_name }} implementation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_platform_widgets: ^3.2.0
  flutter_localizations:
    sdk: flutter
  image_asset_provider:
    path: ../image_asset_provider

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true